/**
 * TypeScript types for metrics and cost tracking (T134)
 *
 * Part of 015-review-polish Phase 5 (Sprint 10 - Metrics & Cost Tracking)
 */

/**
 * Call type classification for token usage tracking
 */
export type CallType = 'task_execution' | 'code_review' | 'coordination' | 'other';

/**
 * Individual token usage record for a single API call
 */
export interface TokenUsage {
  /** Unique identifier for this token usage record */
  id: number;

  /** Task ID if this usage is associated with a task */
  task_id?: number;

  /** Agent ID that made the API call */
  agent_id: string;

  /** Project ID this usage belongs to */
  project_id: number;

  /** Model name (e.g., 'claude-sonnet-4-5-20250929') */
  model_name: string;

  /** Number of input tokens sent to the model */
  input_tokens: number;

  /** Number of output tokens generated by the model */
  output_tokens: number;

  /** Estimated cost in USD based on pricing table */
  estimated_cost_usd: number;

  /** Actual cost if available from API response */
  actual_cost_usd?: number;

  /** Type of API call this usage represents */
  call_type: CallType;

  /** ISO timestamp when this API call occurred */
  timestamp: string;
}

/**
 * Aggregated cost metrics for a project or agent
 */
export interface CostMetrics {
  /** Total cost in USD across all API calls */
  total_cost_usd: number;

  /** Total input tokens across all calls */
  total_input_tokens: number;

  /** Total output tokens across all calls */
  total_output_tokens: number;

  /** Total number of API calls */
  total_calls: number;

  /** ISO timestamp of the oldest usage record */
  start_date: string;

  /** ISO timestamp of the most recent usage record */
  end_date: string;
}

/**
 * Cost breakdown by agent
 */
export interface AgentCostBreakdown {
  /** Agent ID */
  agent_id: string;

  /** Total cost for this agent in USD */
  cost_usd: number;

  /** Number of API calls by this agent */
  call_count: number;

  /** Total tokens (input + output) */
  total_tokens: number;
}

/**
 * Cost breakdown by model
 */
export interface ModelCostBreakdown {
  /** Model name */
  model_name: string;

  /** Total cost for this model in USD */
  cost_usd: number;

  /** Number of API calls using this model */
  call_count: number;

  /** Total tokens (input + output) */
  total_tokens: number;
}

/**
 * Comprehensive cost breakdown for a project
 */
export interface CostBreakdown {
  /** Total cost across all agents and models */
  total_cost_usd: number;

  /** Cost breakdown by agent */
  by_agent: AgentCostBreakdown[];

  /** Cost breakdown by model */
  by_model: ModelCostBreakdown[];
}

/**
 * Agent-specific metrics including cost and token usage
 */
export interface AgentMetrics {
  /** Agent ID */
  agent_id: string;

  /** Project ID (optional if querying single agent) */
  project_id?: number;

  /** Total cost in USD for this agent */
  total_cost_usd: number;

  /** Total input tokens */
  total_input_tokens: number;

  /** Total output tokens */
  total_output_tokens: number;

  /** Total number of API calls */
  total_calls: number;

  /** Breakdown by call type */
  by_call_type: Array<{
    call_type: CallType;
    cost_usd: number;
    call_count: number;
  }>;

  /** Breakdown by model */
  by_model: ModelCostBreakdown[];

  /** ISO timestamp of first API call */
  first_call_at: string;

  /** ISO timestamp of most recent API call */
  last_call_at: string;
}

/**
 * Token usage over time (for time-series charts)
 */
export interface TokenUsageTimeSeries {
  /** Date or datetime label */
  timestamp: string;

  /** Input tokens for this time period */
  input_tokens: number;

  /** Output tokens for this time period */
  output_tokens: number;

  /** Total tokens (input + output) */
  total_tokens: number;

  /** Cost for this time period */
  cost_usd: number;
}

/**
 * Query parameters for fetching token usage records
 */
export interface TokenUsageQueryParams {
  /** Project ID to filter by */
  project_id?: number;

  /** Agent ID to filter by */
  agent_id?: string;

  /** Start date (ISO string) */
  start_date?: string;

  /** End date (ISO string) */
  end_date?: string;

  /** Call type to filter by */
  call_type?: CallType;

  /** Limit number of results */
  limit?: number;
}
